package pl.edu.agh.ontology.generator.application.domain.impl;

import pl.edu.agh.ontology.generator.application.domain.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultOnClickListener <br>
 * @version generated on Thu May 30 23:34:55 CEST 2013 by skywalker
 */
public class DefaultOnClickListener extends WrappedIndividualImpl implements OnClickListener {

    public DefaultOnClickListener(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





}
