package pl.edu.agh.eaiib.androidonotology.impl;

import pl.edu.agh.eaiib.androidonotology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultOnClickListener <br>
 * @version generated on Tue May 28 22:44:11 CEST 2013 by Michal
 */
public class DefaultOnClickListener extends WrappedIndividualImpl implements OnClickListener {

    public DefaultOnClickListener(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasListeners
     */
     
    public Collection<? extends Listener> getHasListeners() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASLISTENERS,
                                               DefaultListener.class);
    }

    public boolean hasHasListeners() {
	   return !getHasListeners().isEmpty();
    }

    public void addHasListeners(Listener newHasListeners) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASLISTENERS,
                                       newHasListeners);
    }

    public void removeHasListeners(Listener oldHasListeners) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASLISTENERS,
                                          oldHasListeners);
    }


}
