package pl.edu.agh.eaiib.androidonotology.impl;

import pl.edu.agh.eaiib.androidonotology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultApplication <br>
 * @version generated on Tue May 28 22:44:11 CEST 2013 by Michal
 */
public class DefaultApplication extends WrappedIndividualImpl implements Application {

    public DefaultApplication(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





}
