package pl.edu.agh.eaiib.androidonotology.impl;

import pl.edu.agh.eaiib.androidonotology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTextView <br>
 * @version generated on Tue May 28 22:55:10 CEST 2013 by Michal
 */
public class DefaultTextView extends WrappedIndividualImpl implements TextView {

    public DefaultTextView(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.agh.edu.pl/eaiib/android/ontology#hasStructure
     */
     
    public Collection<? extends TextView> getHasStructure() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASSTRUCTURE,
                                               DefaultTextView.class);
    }

    public boolean hasHasStructure() {
	   return !getHasStructure().isEmpty();
    }

    public void addHasStructure(TextView newHasStructure) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASSTRUCTURE,
                                       newHasStructure);
    }

    public void removeHasStructure(TextView oldHasStructure) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASSTRUCTURE,
                                          oldHasStructure);
    }


}
