package pl.edu.agh.ontology.generator.application.domain;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Application <br>
 * @version generated on Thu May 30 23:34:55 CEST 2013 by skywalker
 */

public interface Application extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.agh.edu.pl/eaiib/android/ontology#hasMainActivity
     */
     
    /**
     * Gets all property values for the hasMainActivity property.<p>
     * 
     * @returns a collection of values for the hasMainActivity property.
     */
    Collection<? extends MainActivity> getHasMainActivity();

    /**
     * Checks if the class has a hasMainActivity property value.<p>
     * 
     * @return true if there is a hasMainActivity property value.
     */
    boolean hasHasMainActivity();

    /**
     * Adds a hasMainActivity property value.<p>
     * 
     * @param newHasMainActivity the hasMainActivity property value to be added
     */
    void addHasMainActivity(MainActivity newHasMainActivity);

    /**
     * Removes a hasMainActivity property value.<p>
     * 
     * @param oldHasMainActivity the hasMainActivity property value to be removed.
     */
    void removeHasMainActivity(MainActivity oldHasMainActivity);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
