package pl.edu.agh.ontology.generator.application.domain;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MainActivity <br>
 * @version generated on Thu May 30 23:34:55 CEST 2013 by skywalker
 */

public interface MainActivity extends Activity {

    /* ***************************************************
     * Property http://www.agh.edu.pl/eaiib/android/ontology#hasStructure
     */
     
    /**
     * Gets all property values for the hasStructure property.<p>
     * 
     * @returns a collection of values for the hasStructure property.
     */
    Collection<? extends TextView> getHasStructure();

    /**
     * Checks if the class has a hasStructure property value.<p>
     * 
     * @return true if there is a hasStructure property value.
     */
    boolean hasHasStructure();

    /**
     * Adds a hasStructure property value.<p>
     * 
     * @param newHasStructure the hasStructure property value to be added
     */
    void addHasStructure(TextView newHasStructure);

    /**
     * Removes a hasStructure property value.<p>
     * 
     * @param oldHasStructure the hasStructure property value to be removed.
     */
    void removeHasStructure(TextView oldHasStructure);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
