package pl.edu.agh.eaiib.androidonotology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Listener <br>
 * @version generated on Tue May 28 22:55:10 CEST 2013 by Michal
 */

public interface Listener extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.agh.edu.pl/eaiib/android/ontology#hasListeners
     */
     
    /**
     * Gets all property values for the hasListeners property.<p>
     * 
     * @returns a collection of values for the hasListeners property.
     */
    Collection<? extends Listener> getHasListeners();

    /**
     * Checks if the class has a hasListeners property value.<p>
     * 
     * @return true if there is a hasListeners property value.
     */
    boolean hasHasListeners();

    /**
     * Adds a hasListeners property value.<p>
     * 
     * @param newHasListeners the hasListeners property value to be added
     */
    void addHasListeners(Listener newHasListeners);

    /**
     * Removes a hasListeners property value.<p>
     * 
     * @param oldHasListeners the hasListeners property value to be removed.
     */
    void removeHasListeners(Listener oldHasListeners);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
