package pl.edu.agh.eaiib.androidonotology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: MainActivity <br>
 * @version generated on Tue May 28 22:55:10 CEST 2013 by Michal
 */

public interface MainActivity extends Activity {

    /* ***************************************************
     * Property http://www.agh.edu.pl/eaiib/android/ontology#hasMainActivity
     */
     
    /**
     * Gets all property values for the hasMainActivity property.<p>
     * 
     * @returns a collection of values for the hasMainActivity property.
     */
    Collection<? extends Activity> getHasMainActivity();

    /**
     * Checks if the class has a hasMainActivity property value.<p>
     * 
     * @return true if there is a hasMainActivity property value.
     */
    boolean hasHasMainActivity();

    /**
     * Adds a hasMainActivity property value.<p>
     * 
     * @param newHasMainActivity the hasMainActivity property value to be added
     */
    void addHasMainActivity(Activity newHasMainActivity);

    /**
     * Removes a hasMainActivity property value.<p>
     * 
     * @param oldHasMainActivity the hasMainActivity property value to be removed.
     */
    void removeHasMainActivity(Activity oldHasMainActivity);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
