package pl.edu.agh.eaiib.androidonotology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun May 19 20:09:37 CEST 2013 by Michal
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Activity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_ACTIVITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Activity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Application
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPLICATION.<p>
     * 
     */
    public static final OWLClass CLASS_APPLICATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Application"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Application1
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPLICATION1.<p>
     * 
     */
    public static final OWLClass CLASS_APPLICATION1 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Application1"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Button
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUTTON.<p>
     * 
     */
    public static final OWLClass CLASS_BUTTON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Button"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#EditText
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EDITTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_EDITTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#EditText"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Listener
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LISTENER.<p>
     * 
     */
    public static final OWLClass CLASS_LISTENER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#Listener"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#MainActivity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAINACTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_MAINACTIVITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#MainActivity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#OnClickListener
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ONCLICKLISTENER.<p>
     * 
     */
    public static final OWLClass CLASS_ONCLICKLISTENER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#OnClickListener"));

    /* ***************************************************
     * Class http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#TextView
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEXTVIEW.<p>
     * 
     */
    public static final OWLClass CLASS_TEXTVIEW = factory.getOWLClass(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#TextView"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasListeners
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLISTENERS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLISTENERS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasListeners"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasMainActivity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMAINACTIVITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMAINACTIVITY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasMainActivity"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasStructure
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTRUCTURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTRUCTURE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasStructure"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasHint
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASHINT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASHINT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasHint"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasIcon
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASICON.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASICON = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasIcon"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasLabel
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLABEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasLabel"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTEXT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasText"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasTheme
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTHEME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTHEME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/michal/ontologies/2013/4/untitled-ontology-15#hasTheme"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
